theme: jekyll-theme-cayman
title: [Ddux - The next generation react state manager]
description: [The next generation react state manager. Faster better and easier to use. Handle states with single line code. Avoid passing props between multilevel grandchild]
show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]
